### PR TITLE
Clarify the "save page" button

### PR DESCRIPTION
**Pull request by ike709**
image

### CODE REVIEW

**Review by alexkar598 — CHANGES_REQUESTED** [review]
generic.savepage should be Save Page, change the id

**Comment by ike709** [comment]
sounds like a lot of work

**Comment by ike709** [comment]
See https://github.com/tgstation/tgstation-server-webpanel/issues/130

**Comment by alexkar598** [comment]
Its 3 edits in 2 files, i believe in you

**Pull request closed without merging**
