### PR TITLE
IPB OAuth Login + DD restart dump toggle

### PR DESCRIPTION
**Pull request by AffectedArc07**
Adds a button for the IPB support stuff.

Its using an FA icon for now, can make it use a proper SVG if you wish.

DNM until the TGS API release is done.

### CODE REVIEW

**Comment by Cyberboss** [comment]
In this image it shows the name as `InvisionCommunity` do you think you could do the work to get the space added in there please?
image

**Comment by Cyberboss** [comment]
It looks like it might be done already?

**Comment by AffectedArc07** [comment]
> In this image it shows the name as `InvisionCommunity` do you think you could do the work to get the space added in there please? image

Ill figure that out once the API part is in.

**Comment by AffectedArc07** [comment]
image

IPB signin now works, and I also added the dump toggle to the DD page to make it 9.5.0 compliant.

**Review by Cyberboss — APPROVED** [review]

**Review by alexkar598 — APPROVED** [review]
As long as it works properly

Probably need to figure out a way of locking out options that dont match the tgs version but that's out of scope for this pr

**Comment by AffectedArc07** [comment]
> 

Can confirm it works, will demo if you wish

**Comment by Cyberboss** [comment]
Idk how to publish versions so it's up to Alex

**Pull request merged**
