### PR TITLE
Very minor styling tweaks

### PR DESCRIPTION
**Pull request by AffectedArc07**
Cleans up the dropdown on the right
image
It gives things a higher contrast colour, and makes spelling of `Purge Client Cache` more consistent

### CODE REVIEW

**Comment by tgstation-server** [comment]
You currently have a negative Fix/Feature pull request delta of -9. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

**Comment by AffectedArc07** [comment]
> You currently have a negative Fix/Feature pull request delta of -9. Maintainers may close this PR at will. Fixing issues or improving the codebase will improve this score.

go do one

**Comment by alexkar598** [comment]
Color is kinda eyerape but w/e, its better this way

**Comment by tgstation-server** [comment]
Your Fix/Feature pull request delta is currently below zero (-11). Maintainers may close future Feature/Tweak/Balance PRs. Fixing issues or helping to improve the codebase will raise this score.

**Pull request merged**
